CREATE TABLE ERS_USERS_ROLES (
    UR_ID NUMBER PRIMARY KEY,
    UR_ROLE VARCHAR2(40)
);

CREATE TABLE ERS_USERS (
    U_ID NUMBER PRIMARY KEY,
    U_USERNAME VARCHAR2(40),
    U_PASSWORD VARCHAR2(40),
    U_FIRSTNAME VARCHAR2(30),
    U_LASTNAME VARCHAR2(30),
    U_EMAIL VARCHAR2(100),
    UR_ID NUMBER,
    FOREIGN KEY (UR_ID) REFERENCES ERS_USERS_ROLES(UR_ID)
);

CREATE SEQUENCE SQ_ERS_REIMBURSE
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_ERS_USERS
START WITH 1
INCREMENT BY 1;
/


CREATE SEQUENCE SQ_ERS_RIEMB_STATUS
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_ERS_USERS_ROLES
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_REIMBURSE_IN
BEFORE INSERT ON ERS_REIMBURSEMENTS
FOR EACH ROW
    BEGIN
    SELECT SQ_ERS_REIMBURSE.NEXTVAL INTO :NEW.R_ID FROM DUAL;
    
END;
/

CREATE OR REPLACE TRIGGER TR_USERS_IN
BEFORE INSERT ON ERS_USERS
FOR EACH ROW
    BEGIN
    SELECT SQ_ERS_USERS.NEXTVAL INTO :NEW.U_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TR_REIMBURSE_STATUS
BEFORE INSERT ON ERS_REIMBURSEMENT_STATUS
FOR EACH ROW
    BEGIN
    SELECT SQ_ERS_RIEMB_STATUS.NEXTVAL INTO :NEW.RS_ID FROM DUAL;
    
END;
/
CREATE OR REPLACE TRIGGER TR_USER_ROLES_IN
BEFORE INSERT ON ERS_USERS_ROLES
FOR EACH ROW
BEGIN
    SELECT SQ_ERS_USERS_ROLES.NEXTVAL INTO :NEW.UR_ID FROM DUAL; 
END;
/

CREATE OR REPLACE PROCEDURE INSERT_RECIEPT(RRECIEPT IN BLOB) AS
BEGIN
    INSERT INTO ERS_REIMBURSEMENTS(R_RECEIPT) VALUES(RRECIEPT);
END;
/
CREATE OR REPLACE PROCEDURE GET_RECEIPT (RID IN NUMBER, RRECEIPT OUT BLOB) AS
BEGIN
    SELECT R_RECEIPT INTO RRECEIPT FROM ERS_REIMBURSEMENTS WHERE R_ID = RID;
END;
/
CREATE OR REPLACE PROCEDURE REQUEST_REIMB (RAMOUNT IN NUMBER, RDESCIPTION IN VARCHAR2, RUIDAUTHOR IN VARCHAR2, RTTYPE NUMBER) AS
BEGIN
INSERT INTO ERS_REIMBURSEMENTS(R_AMOUNT, R_DESCRIPTION, U_ID_AUTHOR, RT_TYPE)  VALUES (RAMOUNT, RDESCIPTION, RUIDAUTHOR, RTTYPE);
END;
/
CREATE OR REPLACE PROCEDURE INSERT_USER (UUSERNAME IN VARCHAR2, UPASSWORD IN VARCHAR2) AS
BEGIN
INSERT INTO ERS_USERS(U_USERNAME, U_PASSWORD) VALUES (UUSERNAME, UPASSWORD);
END;
/
CREATE OR REPLACE PROCEDURE GET_RESOLVED_REIMB AS
BEGIN
    SELECT U_ID_RESOLVER
    FROM ERS_REIMBURSEMENTS
    WHERE (SELECT UR_ID FROM ERS_USERS_ROLES) = 'RESOLVED';
    
END;
/


